

with open('maze_map0.txt', 'w') as outfile:
    outfile.write('0\n')
    # outfile.write('3 5 -3\n')
    # outfile.write('5 14 -40\n')
    # outfile.write('9 6 -100\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('xSx        x                  x\n')
    outfile.write('x x xxxxx  x   xxx  xxxxx  x  x\n')
    outfile.write('x x   x x xxxxxx    x   x  x  x\n')
    outfile.write('x xxx x x      x xxxx  xx  x  x\n')
    outfile.write('x       xxxxx  x    x  x   x  x\n')
    outfile.write('x xxxxxxx  x   x    x  x   x  x\n')
    outfile.write('x x        x        x  xx  x  x\n')
    outfile.write('x x        xxxxxxxxxx   x  x  x\n')
    outfile.write('x x                     x  x  x\n')
    outfile.write('x xxxxxx    x  x        x  x  x\n')
    outfile.write('x      x    x  x xxx  x x  x  x\n')
    outfile.write('xxx         x  xxx    x xxxx  x\n')
    outfile.write('x   x       x    x   xx        \n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')

with open('maze_map1.txt', 'w') as outfile:
    outfile.write('0\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('xS                            x\n')
    outfile.write('x                          x  x\n')
    outfile.write('x                          x  x\n')
    outfile.write('x                          x  x\n')
    outfile.write('x                          x  x\n')
    outfile.write('x                          x  x\n')
    outfile.write('x                          x  x\n')
    outfile.write('x                          x  x\n')
    outfile.write('x                          x  x\n')
    outfile.write('x                          x  x\n')
    outfile.write('x                          x  x\n')
    outfile.write('x       xxxxxxxxxxxxxxxxxxxx  x\n')
    outfile.write('x                              \n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')

with open('maze_map2.txt', 'w') as outfile:
    outfile.write('0\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('xSx  x      x          x     x    x    x\n')
    outfile.write('x x  xxxxx  x     xxxxxx   xxx    x xx x\n')
    outfile.write('x x  x      x          x     x    x  x x\n')
    outfile.write('x x  x      xxxxx      xxx   x    x  x x\n')
    outfile.write('x x  x      x          x     x    x  x x\n')
    outfile.write('x    x  x   x      x            x x  x x\n')
    outfile.write('x    x  x   x      x   x      xxx xxxx x\n')
    outfile.write('x x  x  x  xxxx    x   xxxxx    x x  x x\n')
    outfile.write('x x  x  x  xxxxxx  x   x      xxx    x x\n')
    outfile.write('x x  x  x  x    x  x   x             x x\n')
    outfile.write('x x     x  x xx x  x   xxxxxxxxxx   xx x\n')
    outfile.write('xxxxxxxxx  x x  x            x         x\n')
    outfile.write('x          x x  x       xxxxxx         x\n')
    outfile.write('xxxx       x xxxxxxxx        x     xxx x\n')
    outfile.write('x                          xxx      x  x\n')
    outfile.write('x x  xxxxxxxxxxxxxxxxxxx     x      x  x\n')
    outfile.write('x x        x        x      xxx      x  x\n')
    outfile.write('x x    x         x           x    x     \n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')


with open('maze_map3.txt', 'w') as outfile:
    outfile.write('0\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('x x    x   x    x     \n')
    outfile.write('x x x  x x x x  x xxxx\n')
    outfile.write('x x x  x x x x  x x xx\n')
    outfile.write('  x x  x x x x  xxx  x\n')
    outfile.write('x x x  x x x x  xx   x\n')
    outfile.write('x x x  x x x x  xx  xx\n')
    outfile.write('x x x  x x x x  x    x\n')
    outfile.write('x   x  x x x x  x Sx x\n')
    outfile.write('x                  x x\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxx')

with open('maze_map4.txt', 'w') as outfile:
    outfile.write('0\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('x                      x\n')
    outfile.write('x                      x\n')
    outfile.write('x  xxxxxxxxxxxxxxxxxx  x\n')
    outfile.write('x  x                x  x\n')
    outfile.write('x  x                x  x\n')
    outfile.write('x  x  xxxxxxxxxxxx  x  x\n')
    outfile.write('x  x  x          x  x  x\n')
    outfile.write('x  x  x  xxxxxx  x  x  x\n')
    outfile.write('x  x  x  x  S x  x  x  x\n')
    outfile.write('x  x  x  x       x  x  x\n')
    outfile.write('x  x  x  xxxxxxxxx  x  x\n')
    outfile.write('x  x  x             x  x\n')
    outfile.write('x  x  xxxxxxxxxxxxxxx  x\n')
    outfile.write('x  x                   x\n')
    outfile.write('x  x                   x\n')
    outfile.write('x  xxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('x                      x\n')
    outfile.write('x                       \n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxx')

with open('maze_map5.txt', 'w') as outfile:
    outfile.write('2\n')
    outfile.write('1 19 -25\n')
    outfile.write('9 6 -4\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('xSx        x                  x\n')
    outfile.write('x x xxxxx  x   xxx  xxxxx  x  x\n')
    outfile.write('x x   x x xxxxxx    x   x  x  x\n')
    outfile.write('x xxx x x      x xxxx  xx  x  x\n')
    outfile.write('x       xxxxx  x    x  x   x  x\n')
    outfile.write('x xxxxxxx  x   x    x  x   x  x\n')
    outfile.write('x x        x        x  xx  x  x\n')
    outfile.write('x x        xxxxxxxxxx   x  x  x\n')
    outfile.write('x x                     x  x  x\n')
    outfile.write('x xxxxxx    x  x        x  x  x\n')
    outfile.write('x      x    x  x xxx  x x  x  x\n')
    outfile.write('xxx         x  xxx    x xxxx  x\n')
    outfile.write('x   x       x    x   xx        \n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')

with open('maze_map6.txt', 'w') as outfile:
    outfile.write('5\n')
    outfile.write('2 23 -10\n')
    outfile.write('4 5 -4\n')
    outfile.write('7 22 -20\n')
    outfile.write('9 15 -15\n')
    outfile.write('13 10 -30\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('xS                            x\n')
    outfile.write('x                          x  x\n')
    outfile.write('x                          x  x\n')
    outfile.write('x                          x  x\n')
    outfile.write('x                          x  x\n')
    outfile.write('x                          x  x\n')
    outfile.write('x                          x  x\n')
    outfile.write('x                          x  x\n')
    outfile.write('x                          x  x\n')
    outfile.write('x                          x  x\n')
    outfile.write('x                          x  x\n')
    outfile.write('x       xxxxxxxxxxxxxxxxxxxx  x\n')
    outfile.write('x                              \n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')

with open('maze_map7.txt', 'w') as outfile:
    outfile.write('10\n')
    outfile.write('10 1 -10\n')
    outfile.write('18 1 -10\n')
    outfile.write('1 3 -10\n')
    outfile.write('1 6 -10\n')
    outfile.write('1 24 -10\n')
    outfile.write('17 10 -10\n')
    outfile.write('18 13 -10\n')
    outfile.write('12 27 -10\n')
    outfile.write('1 35 -10\n')
    outfile.write('8 35 -10\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('xSx  x      x          x     x    x    x\n')
    outfile.write('x x  xxxxx  x     xxxxxx   xxx    x xx x\n')
    outfile.write('x x  x      x          x     x    x  x x\n')
    outfile.write('x x  x      xxxxx      xxx   x    x  x x\n')
    outfile.write('x x  x      x          x     x    x  x x\n')
    outfile.write('x    x  x   x      x            x x  x x\n')
    outfile.write('x    x  x   x      x   x      xxx xxxx x\n')
    outfile.write('x x  x  x  xxxx    x   xxxxx    x x  x x\n')
    outfile.write('x x  x  x  xxxxxx  x   x      xxx    x x\n')
    outfile.write('x x  x  x  x    x  x   x             x x\n')
    outfile.write('x x     x  x xx x  x   xxxxxxxxxx   xx x\n')
    outfile.write('xxxxxxxxx  x x  x            x         x\n')
    outfile.write('x          x x  x       xxxxxx         x\n')
    outfile.write('xxxx       x xxxxxxxx        x     xxx x\n')
    outfile.write('x                          xxx      x  x\n')
    outfile.write('x x  xxxxxxxxxxxxxxxxxxx     x      x  x\n')
    outfile.write('x x        x        x      xxx      x  x\n')
    outfile.write('x x    x         x           x    x     \n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')

with open('maze_map8.txt', 'w') as outfile:
    outfile.write('0\n')
    # outfile.write('3 5 -3\n')
    # outfile.write('5 14 -40\n')
    # outfile.write('9 6 -100\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('xSx        x                  x\n')
    outfile.write('x x xxxxx  x   xxx  xxxxx  x  x\n')
    outfile.write('x x   x x xxxxxx    x   x  x  x\n')
    outfile.write('x xxx x x      x xxxx  xx  x  x\n')
    outfile.write('x       xxxxx  x    x  x   x  x\n')
    outfile.write('x xxxxxxx  x   x    x  x   x  x\n')
    outfile.write('x x        x        x  xx  x  x\n')
    outfile.write('x x    T   xxxxxxxxxx   x  x  x\n')
    outfile.write('x x                     x  x Tx\n')
    outfile.write('x xxxxxx    x  x        x  x  x\n')
    outfile.write('x      x    x  x xxx  x x  x  x\n')
    outfile.write('xxx         x  xxx    x xxxx  x\n')
    outfile.write('x   x       x    x   xx        \n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')